#!/usr/bin/env node
/**
 * build-content.mjs — content/projects/*.json + content/info.json ->
 * assets/content.js, setting window.JC_CONTENT. Mirrors prepare-images.mjs's
 * assets/images.js pattern: a plain <script> tag, not fetch(), so the site
 * still opens directly from the filesystem (see README).
 *
 *   node tools/build-content.mjs
 *
 * tools/placeholder-tones.json (tone/overlay/gal, design-only — see
 * migrate-content.mjs) is merged in per project when present. It is not
 * under content/, so the CMS never sees or touches it.
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const PROJECTS_DIR = "content/projects";
const INFO_FILE = "content/info.json";
const TONES_FILE = "tools/placeholder-tones.json";
const OUT = "assets/content.js";

async function loadProjects() {
  const files = (await readdir(PROJECTS_DIR)).filter(f => f.endsWith(".json")).sort();
  const tones = existsSync(TONES_FILE) ? JSON.parse(await readFile(TONES_FILE, "utf8")) : {};
  const projects = [];
  for (const f of files) {
    // `images` is pipeline input for prepare-images.mjs (raw upload paths),
    // not page data — index.html gets real image paths from window.JC_IMAGES
    // (assets/images.js) instead, so drop it here rather than bloat
    // content.js with duplicate gallery references.
    const { images, ...p } = JSON.parse(await readFile(join(PROJECTS_DIR, f), "utf8"));
    Object.assign(p, tones[p.id] || {});
    projects.push(p);
  }
  // Display order (homepage "newest N", Work index) comes from this field,
  // not file/array position — see the `order` field on each project.
  projects.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
  return projects;
}

/* Reshape the CMS's flatter authoring format for content/info.json back
   into the mixed-shape array index.html's Info-page renderer expects. */
function reshapeSite(info) {
  return {
    intro: info.intro || "",
    bio: info.bio || "",
    portrait: info.portrait || null,
    emails: info.emails || [],
    socials: info.socials || [],
    contact: info.contact || [],
    gear: info.gear || [],
    info: [
      { h: "Selected Clients", list: info.clients || [] },
      { h: "Recognition", list: info.recognition || [] },
      { h: "Approach", body: info.approach || "" },
    ],
    ongoing: (info.ongoing || []).map((o, i) => ({ ...o, tone: ONGOING_TONES[i % ONGOING_TONES.length] })),
  };
}

// ongoing[].tone is a color/design token, not content — assigned here by
// position rather than exposed as a CMS field (same reasoning as SLOTS
// cycling homepage cards by index; see the CMS plan / CLAUDE.md).
const ONGOING_TONES = ["black", "grey", "forest", "sage"];

async function main() {
  const projects = await loadProjects();
  const info = JSON.parse(await readFile(INFO_FILE, "utf8"));
  const site = reshapeSite(info);

  await mkdir("assets", { recursive: true });
  const json = JSON.stringify({ projects, site }, null, 2);
  await writeFile(OUT, `/* Generated by tools/build-content.mjs — do not edit. */\nwindow.JC_CONTENT = ${json};\n`);
  console.log(`Wrote ${OUT} — ${projects.length} project(s), site info.`);
}

main().catch(e => { console.error(e); process.exit(1); });
